# fly.toml app configuration file generated for artube-search on 2023-10-16T21:11:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "artube-search"
primary_region = "ams"

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
  BP_KEEP_FILES = "assets/*"

[env]
  ARTUBE_SEARCH_LISTEN_ADDR = "0.0.0.0:8080"
  ARTUBE_SEARCH_GATEWAY = "https://arweave.net"
  ARTUBE_SEARCH_CACHE_DIR = "/data/cache"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.http_options.response.headers]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET"

