# fly.toml app configuration file generated for artube-search on 2023-10-16T21:11:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "artube-search"
primary_region = "ams"

[mounts]
  source="artube-search_data"
  destination="/data"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  ARTUBE_SEARCH_LISTEN_ADDR = ":3000"
  ARTUBE_SEARCH_GATEWAY = "https://arweave.net"
  ARTUBE_SEARCH_CACHE_FILE = "/data/cache"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

